TITLE = 'Indonesia Holiday'
HOLIDAY_CALENDAR_URI = 'https://kalenderku.id/{year}'
OUTPUT_FORMAT_ICS = 'ics'
OUTPUT_FORMAT_JSON = 'json'
OUTPUT_ACCEPTED_FORMATS = [OUTPUT_FORMAT_ICS, OUTPUT_FORMAT_JSON]
