name: Automation

on:
  schedule:
    - cron: 3 * * * *
  workflow_dispatch:

jobs:
  publish-new-calendar:
    name: Publish Calendar
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    permissions:
      contents: write