name: Automation

on:
  schedule:
    - cron: '1 * * 1 *'
      timezone: 'Asia/Jakarta'
  workflow_dispatch:
    
jobs:
  call-action-publish-calendar:
    name: Call Publish Action
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    permissions:
      contents: write
