name: Automation

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  call-action-publish-calendar:
    name: Publish Calendar
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    permissions:
      contents: write